sudo: required

arch:
  packages:
    - cmake
    - qt5-base

  script:
    - cmake . -DUSE_QT5=ON
    - make

language: cpp

compiler:
  - gcc
  - clang

script:
  - export EDITOR=false
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
