language: cpp

compiler:
  - gcc
  - clang

before_install: sudo apt-get install -qq libqtcore4 qt4-qmake # qtbase5-dev qt5-qmake

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
